apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring-tools
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: init-grafana
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["chown -R 472:472 /var/lib/grafana"]
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          env:
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "Keycloak"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: grafana-keycloak-config
                  key: client_id
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-keycloak-secret
                  key: client_secret
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-keycloak-config
                  key: auth_url
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-keycloak-config
                  key: token_url
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-keycloak-config
                  key: api_url
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
